--  Task 5: JOIN with Aggregation — Total Spend per Customer
-- --------------------------------------------------------------------
-- In this query, we combine INNER JOIN with GROUP BY to calculate
-- the total revenue generated by each customer.
-- This is one of the most common SQL patterns used in analytics.

SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    c.country,
    ROUND(SUM(s.quantity * s.price), 2) AS total_spent,
    COUNT(s.order_id) AS total_orders
FROM customers AS c
INNER JOIN sales AS s
    ON c.customer_id = s.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.country
ORDER BY total_spent DESC;

